spring:
  kafka:
    bootstrap-servers: ${bootstrapservers}
    producer:
      client-id: ${agentid}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.n2.util.AvroSerializer
      properties:
        max:
          request:
            size: 2097176
        auto:
          register:
            schemas: false
    template:
      default-topic: ${topic}
    consumer:
      client-id: 4
      group-id: 400
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.n2.util.AvroDeserializer
      properties:
        specific:
          avro:
            reader: true
        auto:
          register:
            schemas: false
spring-kafka-kotlin-file-watch-transfer:
  filepath: ${filepath}
